### ISSUE TITLE
Domain Expired

### ISSUE THREAD

**Issue by lissy93** [aliabdulazeez/test#14]
Heya @nomanoff,
Love your app, and I use it regularly when writing GitHub docs and commit messages, it's been really useful :)
Just noticed today that the domain (https://emojis.ninja) seems to have either expired or become inaccessible. 
And the GH Pages address (https://aliadam.me/emoji-shortcodes-for-markdown) doesn't seem to load either.

<p align="center"><i>Screenshot:</i><br><img width="400" src="https://user-images.githubusercontent.com/1862727/147506143-e0e945af-76f6-4b11-87a7-425965db440b.png" /></p>

**Comment by nomanoff** [comment]
Hello, thanks for pointing it out. I am really happy that it's been useful. 
I have been a little busy lately, so couldn't work on this project for a while. 
I have just updated the domain to https://emoji-ninja.netlify.app/ and now you can use it 😅.
Regarding the old domain, it will no longer be available. Sorry for that inconvenience.

**Comment by lissy93** [comment]
Probably doesn't need the [gfi](https://goodfirstissues.com/about.html) tag, since it's really not a ticket a first time contributor could pick up.
