### ISSUE TITLE
Update footer name

### ISSUE THREAD

**Issue by nomanoff** [aliabdulazeez/test#16]
### Description 📝
The current footer of the website displays the name "Ali Adam." However, it should be updated to display the name "Azizbek Nomonjonov."

### Comment Before Starting 📌
Before you start working on this issue, please leave a comment here expressing your intent to work on it. This will allow me to assign you to the issue and avoid duplication of efforts.

### Instructions 🛠️
Follow these steps to fix the issue:

1. **Fork the Repository:** Start by forking the repository to your own GitHub account.

2. **Install Dependencies:** The project is bootstrapped with create-react-app, so you can install the dependencies using npm. Run the following command in your project directory:
   ```sh
   npm install

3. **Edit Footer Component:**: Locate the footer component in the source code. You can find it by navigating to the appropriate file. Look for the part of the code that generates the footer text.

4. **Update Name:** Replace the existing name "Ali Adam" with "Azizbek Nomonjonov."

5. **Create Pull Request:** After making the change, commit your code and push it to your forked repository. Then, create a pull request targeting the dev branch of the original repository.

6. **Mention Reviewer:** In your pull request description, mention me (@nomanoff) as a reviewer. This will help me notice your contribution faster.

Best of luck with your contribution! 🚀 And don't forget to star the project if you enjoyed the experience! ⭐

### Additional Information ✅

Repository: [link to repository](https://github.com/your-username/emoji-ninja.netlify.app)
Current Footer Text: © 2023 Ali Adam
Updated Footer Text: © 2023 Azizbek Nomonjonov

Let me know if you need any assistance. 
Happy coding! 😄🎉

**Comment by AsharMallick** [comment]
I am working on this

**Comment by nomanoff** [comment]
okay
